# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  - repo: local
    hooks:
      # pylint hook
      - id: pylint-hook
        name: Pylint our python files
        entry: pylint
        language: python
        types: [python]
        args:
          - --rcfile=otter_v2_service/.arcpylint_rcfile
        verbose: true

  - repo: git@github.com:ContextLogic/pre-commit-internal-china.git
    rev: v1.0.12
    hooks:
      # run wish_flask common hook to keep specification
      - id: wish-flask-org-hook

      # run customer test
      - id: python-test-hook
        args:
          - --container=otter-v2-service
          - --fileDirs=./otter_v2_service/__tests__
