---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: otter-v2-service
  namespace: wish-micro
  annotations:
    fluxcd.io/automated: "true"
    # This will be changed by Setonix automatically.
    filter.fluxcd.io/chart-image: "*"
spec:
  releaseName: otter-v2-service
  chart:
    git: git@github.com:ContextLogic/helm-ms-cn.git
    path: charts/simple-micro
    ref: dev
  values:
    image:
      repository: harbor.infra.wish-cn.com/wish/otter-v2-service/api
      tag: <tag>
    fullnameOverride: otter-v2-service
    replicaCount: 1
    servicePort: 8888
    wishAppLabel: otter-v2-service
    serviceAccount:
      # Change this to true if you need to enable it.
      create: false
      # If you are using aws resources, e.g. SQS and S3,
      # please create a Jira ticket to SRE @yiyan to ask for role-arn.
      #annotations:
      #  eks.amazonaws.com/role-arn: <role-arn>
      #  eks.amazonaws.com/audience: sts.amazonaws.com.cn
    podAnnotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port: "8888"
      co.elastic.logs/enabled: 'true'
      katalog-sync.wish.com/service-names: otter-v2-service-pod
      katalog-sync.wish.com/service-port: "8888"
    env:
      - name: FLASK_ENV
        value: dev
    args:
      - /bin/bash
      - -c
      - "/production/otter_v2_service/current/otter_v2_service/bin/entrypoint-api.sh"
    service:
      annotations:
        hermes.wish.com/service-name: otter-v2-service
    ingress:
      # Change this to true if you need to enable it.
      enabled: false
      # Please follow https://wiki.wish.site/display/Infra/1.2+Add+or+update+dns+entry+for+bjs.i.wish.com to apply for dns.
      hosts:
        - host: otter-v2-service.k8sdev.bjs.i.wish.com
          paths:
            - /